pipeline {
    agent {
        label 'nodejs'
    }
    stages {
        stage('Deploy') {
            steps {
                sh '''
                    oc project jmhbva-deploy-strategies oc start-build greeting-service --follow --wait
            ''' }
        }

    // Add the "Deploy" stage here
    }
}
